version: '2'
services:
    config-service:
      container_name: ms-config
      build: 
        context: config-server
        dockerfile: Dockerfile
      image: ms-config
      ports:
        - 8888:8888
      networks: 
        - spring-cloud-network 
    discovery-service:  
      container_name: ms-discovery
      build: 
        context: discovery-server
        dockerfile: Dockerfile
      image: ms-discovery
      ports:
        - 8761:8761
      networks: 
        - spring-cloud-network       
    proxy-service:  
      container_name: ms-proxy
      build: 
        context: proxy-server
        dockerfile: Dockerfile
      image: ms-proxy
      ports:
        - 9999:9999
      networks: 
        - spring-cloud-network  
    product-service:
      container_name: ms-product
      build: 
        context: product-server
        dockerfile: Dockerfile
      image: ms-product
      ports:
        - 9090:9090
      networks: 
        - spring-cloud-network  
networks:
    spring-cloud-network:
        driver: bridge
