version: '2'
services:
    discovery-service:  
      container_name: ms-discovery
      build: 
        context: discovery-server
        dockerfile: Dockerfile
      image: ms-discovery
      ports:
        - 8761:8761
      networks: 
        - spring-cloud-network      
    movie-info-service:
      container_name: ms-movie-info
      build: 
        context: movie-info-service
        dockerfile: Dockerfile
      image: ms-movie-info
      ports:
        - 8082:8082
      networks: 
        - spring-cloud-network  
    rating-data-service:  
      container_name: ms-rating-data
      build: 
        context: rating-data-service
        dockerfile: Dockerfile
      image: ms-rating-data
      ports:
        - 8083:8083
      networks: 
        - spring-cloud-network  
    movie-catalog-service:
      container_name: ms-movie-catalog
      build: 
        context: movie-catalog-service
        dockerfile: Dockerfile
      image: ms-movie-catalog
      ports:
        - 8081:8081
      networks: 
        - spring-cloud-network  
networks:
    spring-cloud-network:
        driver: bridge