pipeline {
    agent any
    //Use Pipeline Utility Steps plugin to read information from pom.xml into env variables
    environment { 
        registryCredential = 'DockerHub_Credentials'
        imagename = 'kemflorent/proxy-service:' // Nom du container docker
        dockerImage = ''
    }
    stages {
        stage('Clone Repository') {
            steps {
               git credentialsId: 'Pipeline_GitHub_Credentials', url: 'https://github.com/kemflorent/msa-jenkins-pipeline.git', branch: 'main'
            }
        }
        stage("Build JAR") {
            steps {
                dir ('proxy-service') {
                    sh 'mvn -B clean package -DskipTests=true'
                }
            }
        }
        stage("Build Docker Image") {
            steps {
                dir ('proxy-service') {
                    script { 
                        dockerImage = docker.build imagename + "${env.BUILD_NUMBER}"
                    }
                }
            }
        }
        stage("Push Docker Image") {
            steps {
                dir ('proxy-service') {
                    script { 
                        docker.withRegistry('https://registry.hub.docker.com', registryCredential ) { 
                            dockerImage.push("${env.BUILD_NUMBER}")
                            dockerImage.push("latest")
                        }
                    }
                }
            }
        }
        stage("Run Docker Image") {
            steps {
                script { 
                    docker.image(imagename + "${env.BUILD_NUMBER}")
                          .run('-p 9999:9999')
                }
            }
        }
        /*stage('Cleaning up') { 
            steps { 
                echo 'Removing unused docker containers and images..'
                sh 'docker ps -aq | xargs --no-run-if-empty docker rm'
                // keep intermediate images as cache, only delete the final image
                sh 'docker images -q | xargs --no-run-if-empty docker rmi'
            }
        } */


        // stage("Testing") {
        //     parallel {
        //         stage("Unit Tests") {
        //             agent { docker 'openjdk:7-jdk-alpine' }
        //             steps {
        //                 sh 'java -version'
        //             }
        //         }
        //         stage("Functional Tests") {
        //             agent { docker 'openjdk:8-jdk-alpine' }
        //             steps {
        //                 sh 'java -version'
        //             }
        //         }
        //         stage("Integration Tests") {
        //             steps {
        //                 sh 'java -version'
        //             }
        //         }
        //     }
        // }  
    }
}